name: Karl Bartel
author: Karl Bartel
markdown: redcarpet
pygments: true
description: Software Developer
email: karl42@gmail.com
title: Karl Bartel
##location: 42°2'16"N   70°12'47"W
baseurl: 

##Make sure to edit the above fields, especially for disqus.

